services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql


  catalogapi:
    build:
      context: ./Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    container_name: catalogapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "50003:80"
    depends_on:
      - catalogdb
